export enum CommandQueryTypes {
  GET_ALL_PRODUCTS = "GET_ALL_PRODUCS",
  CREATE_PRODUCT = "CREATE_PRODUCT",
  RESTOCK_PRODUCT = "RESTOCK_PRODUCT",
  SELL_PRODUCT = "SELL_PRODUCT",
  CREATE_ORDER = "CREATE_ORDER"
}
